name = "secompp-game"
main = "src/server/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8787

[durable_objects]
bindings = [
  { name = "MATCH_ROOM", class_name = "MatchRoom" },
  { name = "MATCHMAKING_QUEUE", class_name = "MatchmakingQueue" },
  { name = "ADMIN_REGISTRY", class_name = "AdminRegistry" }
]

[[migrations]]
tag = "v3"
new_classes = ["AdminRegistry"]

[[d1_databases]]
binding = "DB"
database_name = "secompp-db"
database_id = "secompp-db-id"

[vars]
ADMIN_PASSWORD = "secompp_admin"
